name: golangci-lint

on:
  push:
    branches: [ "main", "v*.*.*" ]
  pull_request:
    branches: [ "main", "v*.*.*" ]

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code.
      - uses: actions/checkout@v4

      # Setup Go environment.
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          # Disable caching to avoid issues with the golangci-lint action's own caching.
          cache: false

      # Install dependencies for eBPF and CGO.
      # eBPF use CGO, so the header files are required to run the lint.
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libbpf-dev libssl-dev linux-tools-common linux-tools-generic

      - name: Generate eBPF Go files
        run: |
          go install github.com/cilium/ebpf/cmd/bpf2go@latest
          
          mkdir -p headers
          bpftool btf dump file /sys/kernel/btf/vmlinux format c > headers/vmlinux.h
          
          go generate ./...
        
      # Run golangci-lint.
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
          # Arguments to use when running the lint.
          # --timeout=5m: Set timeout
          args: --timeout=5m

          # Since CGO is required, the cache key must be exact.
          skip-cache: false